name: Publish Release
on:
  release:
    types: [published]
  push:
    tags:
      - '*'

jobs:
  cargo-publish:
    name: Publish to Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Publish to crates.io
        run: |
          cargo publish --token ${{ secrets.CARGO_API_KEY }}
